<?php
defined('_MRKEN_CMS') or die('Restricted access');
$lang['about_text']                    =   '&laquo;' . functions::checkout(core::$system_set['copyright']) . '&raquo; là diễn đàn dành cho các Wap/Web Master, nơi các Wap/Web Master tiếp cận, học tập và trao đổi về lập trình Wap/Web';
$lang['avatar_change_warning']         =   'Bạn có muốn đặt ảnh này làm ảnh đại diện?';
$lang['forum_rules']                   =   'Quy định diễn đàn';
$lang['forum_rules_text']              =   '<b>1) CẤM:</b><br/><br/><b>1.1</b> Đăng tin quảng cáo.<br/><b>1.2</b> Đăng nội dung liên quan đến vấn đề phân biệt sắc tộc, tôn giáo, quốc gia.<br/><b>1.3</b> Không đăng nội dung thô tục, khiêu dâm, quấy rối tình dục, vu khống, đe dọa người khác.<br/><b>1.4</b> Không được đăng nội dung xúc phạm một chủ thể cụ thể, đặc biệt là thành viên trong diễn đàn.<br/><b>1.5</b> Cố tình giả mạo thành viên khác với bất kỳ mục đích nào.<br/><b>1.6</b> Đăng bài cùng một nội dung nhiều lần trong một hay nhiều chủ đề khác nhau.<br/><b>1.7</b> Đăng lại bài viết hoặc tạo lại chủ đề đã bị xóa bởi Ban quản trị.<br/><b>1.8</b> Đăng bài có nội dung không liên quan đến tiêu đề.<br/><br/><b>2) TUYỆT ĐỐI CẤM:</b><br/><br/><b>2.1</b> Tạo chủ đề than phiền về thành viên hoặc cách hoạt động của điều hành viên. Hãy sử dụng tin nhắn riêng cho vấn đề này<br/><b>2.2</b> Đăng ký nick chứa ký tự gây khó chịu cho người khác<br/><br/><b>3) KHÔNG CHẤP NHẬN:</b><br/><br/><b>3.1</b> Trích dẫn nội dung quá dài hoặc trích dẫn lại một bài đăng chứa một trích dẫn khác.<br/><b>3.2</b> Bài viết tin chỉ chứa liên kết đến các trang web khác. <br/><b>3.3</b> Đăng bài bằng ngôn ngữ không sử dụng chữ cái latin (a-z).<br/><b>3.4</b> Đăng bài không có mục đích: chỉ có biểu tượng vui  hoặc bài như "Ok", "Có ai không?",... <br/><br/>Quy định trên đây có thể thay đổi bất kỳ lúc nào.<br />Quy định này áp dụng cho tất cả các thành viên và Ban quản trị, thành viên vi phạm nhiều lần sẽ bị ban, vi phạm nặng có thể dẫn đến xóa bỏ tài khoản vĩnh viễn.';
$lang['set_to_profile']                =   'Đặt trong một hồ sơ';
$lang['smileys_adm']                   =   'For administration';
$lang['tags']                          =   'BBcode';
$lang['tags_link_name']                =   'Link name';
$lang['tags_faq_text']                 =   '<table cellpadding="2" cellspacing="0"><tr><td align="right"><h3>BBcode</h3></td><td></td></tr><tr><td align="right">[php]...[/php]</td><td>Source code for PHP</td></tr><tr><td align="right">Link</td><td>[url=http://link_address]link name[/url]</td></tr><tr><td align="right">[b]...[/b]</td><td><b>Bold</b></td></tr><tr><td align="right">[i]...[/i]</td><td><i>Italic</i></td></tr><tr><td align="right">[u]...[/u]</td><td><u>Underline</u></td></tr><tr><td align="right">[s]...[/s]</td><td><strike>Strikethrought</strike></td></tr><tr><td align="right">[red]...[/red]</td><td><span style="color:red">Red</span></td></tr><tr><td align="right">[green]...[/green]</td><td><span style="color:green">Green</span></td></tr><tr><td align="right">[blue]...[/blue]</td><td><span style="color:blue">Blue</span></td></tr><tr><td align="right">[c]...[/c]</td><td><span class="quote">Chú thích</span></td></tr></table>';